
all: test_frexp test_nexttoward test_ryu

test_frexp: test_frexp.cpp
	g++ -std=c++17 -o test_frexp test_frexp.cpp

test_nexttoward: test_nexttoward.cpp
	g++ -std=c++17 -o test_nexttoward test_nexttoward.cpp

test_ryu: test_ryu.cpp
	g++ -std=c++17 -o test_ryu test_ryu.cpp
