CXX=$(HOME)/bin/bin/g++ -std=c++2a -g

all: test_frexp test_nexttoward test_ryu

test_frexp: test_frexp.cpp
	$(CXX) -o test_frexp test_frexp.cpp

test_nexttoward: test_nexttoward.cpp
	$(CXX) -o test_nexttoward test_nexttoward.cpp

test_ryu: test_ryu.cpp
	$(CXX) -o test_ryu test_ryu.cpp
